package Rascaldebugger.DebugRunner;

/*Generated by MPS */

import org.rascalmpl.library.Rascal2MPS;
import java.nio.file.Path;
import java.nio.file.Paths;
import io.usethesource.vallang.IConstructor;

public class DebugRunner {

  public static void main(String[] args) {
    Rascal2MPS m = new Rascal2MPS();
    Path p = Paths.get("C:\\Dev\\RascalExample\\src");
    IConstructor rascalAST = m.getAST(p.toUri().toString(), "Abstract", "EXP");
  }
}
